#ifndef SAWS_TELEOP_JOY_PS4_MACROS_HPP
#define SAWS_TELEOP_JOY_PS4_MACROS_HPP

#define PS4_AXIS_LEFT_X 0
#define PS4_AXIS_LEFT_Y 1
#define PS4_AXIS_RIGHT_X 2
#define PS4_AXIS_RIGHT_Y 3
#define PS4_AXIS_L2 4
#define PS4_AXIS_R2 5

#define PS4_BUTTON_X 0
#define PS4_BUTTON_O 1
#define PS4_BUTTON_SQUARE 2
#define PS4_BUTTON_TRIANGLE 3
#define PS4_BUTTON_SHARE 4
#define PS4_BUTTON_PLAYSTATION 5
#define PS4_BUTTON_OPTIONS 6
#define PS4_BUTTON_L3 7
#define PS4_BUTTON_R3 8
#define PS4_BUTTON_L1 9
#define PS4_BUTTON_R1 10
#define PS4_BUTTON_UP 11
#define PS4_BUTTON_DOWN 12
#define PS4_BUTTON_LEFT 13
#define PS4_BUTTON_RIGHT 14
#define PS4_BUTTON_TOUCHPAD 15

#endif
